# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=191, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Category')),
            ],
        ),
    ]
